### ISSUE TITLE
Does it accept blow5 query files 

### ISSUE THREAD

**Issue by sayangoswami** [vshiv18/sigmoni#3]
Hi,

Is Sigmoni supposed to work with blow5 query files? When I tried running it, it gave me the following error even though I have checked (using slow5tools) that the file is in the correct format.

```
[slow5_idx_init::INFO] Index file not found. Creating an index at '/home/sayan/CLionProjects/Playground/extern/slow5lib/test/data/err/no_eof.blow5.idx'.
[slow5_idx_build::ERROR] Malformed blow5 record. Failed to read the record size. Missing blow5 end of file marker. At src/slow5_idx.c:266
26-Jul-24 15:10:21 - pyslow5 - [WARNING]: slow5_idx_load return not 0: -1: ['SLOW5_ERR_EOF', 'End Of File reached']
26-Jul-24 15:10:21 - pyslow5 - [WARNING]: slow5_idx_load return not 0: -1: ['SLOW5_ERR_EOF', 'End Of File reached']
26-Jul-24 15:10:21 - pyslow5 - [WARNING]: slow5_idx_load return not 0: -1: ['SLOW5_ERR_EOF', 'End Of File reached']
26-Jul-24 15:10:21 - pyslow5 - [WARNING]: slow5_idx_load return not 0: -1: ['SLOW5_ERR_EOF', 'End Of File reached']
[slow5_get_rids::ERROR] No slow5 index has been loaded. At src/slow5.c:2552
26-Jul-24 15:10:21 - pyslow5 - [ERROR]: get_read_ids: length of read_ids is 0, something when wrong
26-Jul-24 15:10:21 - pyslow5 - [ERROR]: get_read_ids: length of read_ids is 0, something when wrong
26-Jul-24 15:10:21 - pyslow5 - [ERROR]: get_read_ids: length of read_ids is 0, something when wrong
26-Jul-24 15:10:21 - pyslow5 - [ERROR]: get_read_ids: length of read_ids is 0, something when wrong
26-Jul-24 15:10:21 - pyslow5 - [ERROR]: get_read_ids: returned rids is NULL, something when wrong
26-Jul-24 15:10:21 - pyslow5 - [ERROR]: get_read_ids: returned rids is NULL, something when wrong
26-Jul-24 15:10:21 - pyslow5 - [ERROR]: get_read_ids: returned rids is NULL, something when wrong
26-Jul-24 15:10:21 - pyslow5 - [ERROR]: get_read_ids: returned rids is NULL, something when wrong
Indexing '/home/sayan/CLionProjects/Playground/extern/slow5lib/test/data/err/parse_bad.slow5'
[slow5_hdr_init::ERROR] Malformed slow5 header. Bad minor version '256'. At src/slow5.c:734
[slow5_init::ERROR] Parsing slow5 header of file '/home/sayan/CLionProjects/Playground/extern/slow5lib/test/data/err/version_too_large.slow5' failed. At src/slow5.c:155
Segmentation fault (core dumped)
```

I am not sure how it chose the slow5 library path to `/home/sayan/CLionProjects/Playground/extern/slow5lib`. Can I specify a different slow5 library path?

Thanks in advance for your help.

**Comment by sayangoswami** [comment]
Actually I get the same error even when I use fast5 files. What am I doing wrong?

**Comment by vikshiv** [comment]
Hi, apologies for the late reply. This is likely an issue with some updates to Uncalled (which handles the fast5 and blow5 parsing). I am working on updating Sigmoni to work with the latest Uncalled version (and link to the specific commit so it doesn't break in the future). I'll update here when that's up and running.

**Comment by vikshiv** [comment]
Hi @sayangoswami, apologies again for the delay. I've updated Sigmoni to use the latest version of Uncalled4 (which is stable and shouldn't have future compatibility issues). Please reinstall Uncalled4 following the updated README. I'm working on Slow5 and Pod5 support with the author of Uncalled4, and that should be up shortly. 

Note: Fast5 support will be slightly slower than previously due to change in Fast5 parsing in Uncalled. I'm working on a fix for this, but it may be slower than we report in previous results.

Let me know if you run into any issues!

**Comment by vikshiv** [comment]
Hi @sayangoswami, I just heard from the author of Uncalled that Slow5 support is fixed on the latest commit of Uncalled4 (https://github.com/skovaka/uncalled4). Sigmoni should work with Slow5/Blow5 and Fast5's now. Let me know if you have any issues.

**Comment by sayangoswami** [comment]
Hi Vikram, thanks very much for your help. I just wanted to check one more thing with you. When I try to run `python $SIGMONI_DIR/main.py -i /scratch/Zymo/signal/fast5/ -r /scratch/Zymo/Sigmoni/refs -o /scratch/Zymo/Sigmoni/out -t 32` it fails and returns the following error:
```
  File "/home/sayan/.opt/sigmoni/main.py", line 172, in <module>
    main(args)
  File "/home/sayan/.opt/sigmoni/main.py", line 91, in main
    query_reads(args)
  File "/home/sayan/.opt/sigmoni/main.py", line 110, in query_reads
    sig.write_read_parallel(seq_signal, args.bins, evdt=utils.SIGMAP_EVDT, fname=readfile, threads=args.threads)
  File "/home/sayan/.opt/sigmoni/sigmoni/run_spumoni.py", line 125, in write_read_parallel
    with open(fname, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/Zymo/Sigmoni/out/reads.fa'
```

Is it trying to find `reads.fa` in the output directory? BTW, I had built the index with the following command:
`python $SIGMONI_DIR/index.py -p /scratch/Zymo/Refs-1.fasta -n /scratch/Zymo/Refs-0.fasta --shred 100000 -o /scratch/Zymo/Sigmoni --spumoni-path $SPUMONI_BUILD_DIR/spumoni`

Could you give me a hint as to whats going wrong here? Thanks again for your time.
